version: "3"

services:
  next-app:
    container_name: next-app
    build: ./next-app
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
  fast-server:
    container_name: fast-server
    build: ./fast-server
    volumes:
      - ./fast-server/app:/code/app
    restart: always
    ports:
      - 5000:5000
