version: "3"

services:
  next-app:
    container_name: next-app
    build: ./next-app
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000

