"""update users table

Revision ID: 1050442bf08f
Revises: 776ef62d19fc
Create Date: 2024-03-30 23:19:41.172336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1050442bf08f'
down_revision: Union[str, None] = '776ef62d19fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE role_id_seq START 1000 INCREMENT 1;")
    op.alter_column('users', 'role_id', server_default=sa.text("nextval('role_id_seq'::regclass)"))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_id')
    op.execute("DROP SEQUENCE role_id_seq;")
    pass
    # ### end Alembic commands ###
