"""update users table

Revision ID: 776ef62d19fc
Revises: 0f4952737bb8
Create Date: 2024-03-30 19:34:25.710627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776ef62d19fc'
down_revision: Union[str, None] = '0f4952737bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False, server_default='1000', autoincrement=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'Unassigned'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###
